---
- name: Crowdsec | install_agent_debian | Add CrowdSec repository
  ansible.builtin.deb822_repository:
    name: crowdsec
    types:
      - deb
      - deb-src
    components: main
    suites: any
    uris: https://packagecloud.io/crowdsec/crowdsec/any
    signed_by: https://packagecloud.io/crowdsec/crowdsec/gpgkey
    state: present
    enabled: true

- name: Crowdsec | install_agent_debian | Install CrowdSec agent
  ansible.builtin.apt:
    name:
      - crowdsec
      - crowdsec-firewall-bouncer-iptables
    state: present
    update_cache: true

- name: Crowdsec | install_agent_debian | Install Cloudflare bouncer
  ansible.builtin.apt:
    name: crowdsec-cloudflare-bouncer
    state: present
    update_cache: false
  when: crowdsec_cf_token | length > 0

- name: Crowdsec | install_agent_debian | Configure Cloudflare bouncer
  ansible.builtin.command:
    cmd: 'crowdsec-cloudflare-bouncer -g {{ crowdsec_cf_token }} -o /etc/crowdsec/bouncers/crowdsec-cloudflare-bouncer.yaml'
    creates: /etc/crowdsec/bouncers/crowdsec-cloudflare-bouncer.yaml
  when: crowdsec_cf_token | length > 0
