# - name: Crowdsec | install_bouncers_tarball | Check if bouncer {{ cs_bouncer }} is installed
#   ansible.builtin.stat:
#     path: "{{ cs_install_dir_bouncer }}/{{ cs_bouncer }}"
#   register: bouncer_stat

# - name: Crowdsec | install_bouncers_tarball | Check if CrowdSec agent is installed and return version
#   ansible.utils.cli_parse:
#     command: crowdsec -version
#     parser:
#       name: ansible.netcommon.native
#       template_path: cs-version.yml
#     set_fact: crowdsec_version
#   when: bouncer_stat.stat.exists

- name: Crowdsec | install_bouncers_tarball | Install bouncer {{ cs_bouncer }} (tarball)
  ansible.builtin.debug:
    msg: "TBD"
