---
# EPEL is available via standard repos on modern RHEL/Rocky 8+ if needed.
# - name: Crowdsec | install_agent_rhel | Enable EPEL Repository on Rocky/CentOS 8
#   ansible.builtin.dnf:
#     name: epel-release
#     state: present
#   when: ansible_facts['distribution_major_version'] == '8'

- name: Crowdsec | install_agent_rhel | Install required packages
  ansible.builtin.dnf:
    name:
      - yum-utils
    state: present

# https://packagecloud.io/crowdsec/crowdsec/install#manual-rpm
- name: Crowdsec | install_agent_rhel | Add CrowdSec repository
  ansible.builtin.yum_repository:
    name: crowdsec
    description: crowdsec repository
    gpgkey:
      - https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-B78D1222C9AD2D5D.pub.gpg
      - https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-FED78314A2468CCF.pub.gpg
    baseurl: https://packagecloud.io/crowdsec/crowdsec/el/$releasever/$basearch/
    state: present
    file: crowdsec

- name: Crowdsec | install_agent_rhel | Install CrowdSec agent
  ansible.builtin.dnf:
    name: crowdsec
    state: present
    update_cache: true
