# - name: Enable EPEL Repository on CentOS 8
#   ansible.builtin.dnf:
#     name: epel-release
#     state: latest
#   when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'
# - name: Enable EPEL Repository on CentOS 7
#   ansible.builtin.yum:
#     name: epel-release
#     state: latest
#   when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

- name: Install required packages
  ansible.builtin.yum:
    name:
    # - pygpgme
      - yum-utils
    state: present

# https://packagecloud.io/crowdsec/crowdsec/install#manual-deb
- name: Add crowdsec apt repository
  ansible.builtin.yum_repository:
    name: crowdsec
    description: crowdsec repository
    gpgkey:
      - https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-B78D1222C9AD2D5D.pub.gpg
      - https://packagecloud.io/crowdsec/crowdsec/gpgkey/crowdsec-crowdsec-FED78314A2468CCF.pub.gpg
    baseurl: https://packagecloud.io/crowdsec/crowdsec/el/$releasever/$basearch/
    state: present
    file: crowdsec

- name: Install crowdsec
  ansible.builtin.dnf:
    name: crowdsec
    state: present
    update_cache: true
